filename = input("Enter search results file: ")
INPUTFILE = open(filename, "r")
line = INPUTFILE.readline()
line = line.lower()
outfile = input("Enter input file: ")
OUTPUTFILE = open(outfile, "w")
OUTPUTFILE.write(line)
OUTPUTFILE.close()
INPUTFILE.close()
